<?php

namespace App\Http\Controllers;

use App\Models\Episode;
use Illuminate\Http\Response;

class PodcastFeedController extends Controller
{
    public function index(): Response
    {
        $site = [
            'title' => config('app.name', 'Powerpod'),
            'link'  => rtrim(config('app.url'), '/'),
            'desc'  => 'Podcast feed generated by Powerpod',
            'lang'  => 'en-us',
        ];

        $episodes = Episode::query()
            ->where('status', 'published')
            ->orderByDesc('published_at')
            ->orderByDesc('id')
            ->limit(100)
            ->get();

        $xml = view('feed.podcast', compact('site', 'episodes'))->render();

        return response($xml, 200)->header('Content-Type', 'application/rss+xml; charset=UTF-8');
    }
}
